// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7scDORBAbPOkCs4l615TQN4R-VV5S2RE',
    appId: '1:1097704288202:web:daac5c99589ba9decf2933',
    messagingSenderId: '1097704288202',
    projectId: 'pulseconnect-e1ee0',
    authDomain: 'pulseconnect-e1ee0.firebaseapp.com',
    storageBucket: 'pulseconnect-e1ee0.firebasestorage.app',
    measurementId: 'G-WKL6QZ18EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0f959pJReXZfiVOfRqYCIZoGMyvX_E9E',
    appId: '1:1097704288202:android:491e5ab5f9349f84cf2933',
    messagingSenderId: '1097704288202',
    projectId: 'pulseconnect-e1ee0',
    storageBucket: 'pulseconnect-e1ee0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASfCSIKhBmf7v6MCPNlXLQ467Rgdcr78Q',
    appId: '1:1097704288202:ios:9b3fdb1fe7211b90cf2933',
    messagingSenderId: '1097704288202',
    projectId: 'pulseconnect-e1ee0',
    storageBucket: 'pulseconnect-e1ee0.firebasestorage.app',
    iosBundleId: 'com.example.pulseConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASfCSIKhBmf7v6MCPNlXLQ467Rgdcr78Q',
    appId: '1:1097704288202:ios:9b3fdb1fe7211b90cf2933',
    messagingSenderId: '1097704288202',
    projectId: 'pulseconnect-e1ee0',
    storageBucket: 'pulseconnect-e1ee0.firebasestorage.app',
    iosBundleId: 'com.example.pulseConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7scDORBAbPOkCs4l615TQN4R-VV5S2RE',
    appId: '1:1097704288202:web:e630259ee001504acf2933',
    messagingSenderId: '1097704288202',
    projectId: 'pulseconnect-e1ee0',
    authDomain: 'pulseconnect-e1ee0.firebaseapp.com',
    storageBucket: 'pulseconnect-e1ee0.firebasestorage.app',
    measurementId: 'G-RPT2ZL3QKT',
  );
}
